// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListWebhooksRequest {
    /** Inspect one agent's webhook (omit to list all) */
    agent_id?: string | null;
}
