// This file was auto-generated by Fern from our API Definition.

import type * as AgentlineApi from "../../../../index.js";

/**
 * @example
 *     {
 *         url: "url",
 *         agent_id: "agent_id"
 *     }
 */
export interface WebhookConfig {
    /** HTTPS URL that will receive this agent's events as signed JSON POSTs. Setting this replaces any existing webhook for the agent. */
    url: string;
    /** ID of the agent whose events this webhook receives. Each agent may have at most one webhook. */
    agent_id: string;
    /** Optional HMAC signing secret. Auto-generated if omitted. Used to verify the signature header on delivered payloads. */
    secret?: string | null;
    /** Header name for the HMAC-SHA256 signature of the raw body. Defaults to 'X-Webhook-Signature' (natively verified by Hermes, OpenClaw, and other agent platforms). Set to 'X-Hub-Signature-256' for GitHub-style verification, or any custom header name your platform expects. Omit to keep the existing value when updating. */
    signature_header?: string | null;
    /** Live relay protocol. 'agentline-relay/1' (default): one call.utterance POST per task, answer in the response body or via push. 'agentline-relay/2': typed POSTs (call.session.start, call.task.open, call.task.amend, call.task.cancel, call.session.end); answer only via POST /v1/calls/{call_id}/context and return 202 quickly. Omit to keep the existing value when updating. */
    protocol?: WebhookConfig.Protocol | null;
    /** Relay v2 capabilities. Omit to keep the existing value when updating. */
    capabilities?: AgentlineApi.WebhookCapabilities | null;
}

export namespace WebhookConfig {
    export const Protocol = {
        AgentlineRelay1: "agentline-relay/1",
        AgentlineRelay2: "agentline-relay/2",
    } as const;
    export type Protocol = (typeof Protocol)[keyof typeof Protocol];
}
