// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         voice_id: "voice_id"
 *     }
 */
export interface VoiceSettingUpdate {
    /** TTS voice preset name (e.g. 'female-1', 'male-1') or Cartesia voice UUID */
    voice_id: string;
}
