// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListMessagesRequest {
    /** Filter messages by AI agent ID */
    agent_id?: string | null;
    /** Filter messages by conversation thread ID */
    conversation_id?: string | null;
    /** Maximum number of messages to return (1-200) */
    limit?: number;
    /** Number of messages to skip for pagination */
    offset?: number;
}
