// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         agent_id: "agent_id",
 *         to_number: "to_number",
 *         body: "body"
 *     }
 */
export interface MessageSend {
    /** ID of the AI agent sending the SMS (e.g. 'agt_abc123') */
    agent_id: string;
    /** Destination phone number in E.164 format (e.g. '+12125551234') */
    to_number: string;
    /** SMS message text content */
    body: string;
    /** URL of media to attach (MMS) */
    media_url?: string | null;
    /** Specific phone number ID to send from; defaults to the agent's assigned number */
    from_number_id?: string | null;
}
