// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface GetExpenditureBillingRequest {
    /** Time period: 'current_month', 'last_month', 'all_time', or 'YYYY-MM' */
    period?: string;
}
