// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListCallChargesBillingRequest {
    /** Maximum number of call charges to return (1-200) */
    limit?: number;
    /** Number of records to skip for pagination */
    offset?: number;
}
