// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         name: "name"
 *     }
 */
export interface AgentCreate {
    /** Display name for the AI voice agent */
    name: string;
    /** Default instructions for the agent's personality and behavior on ALL calls (inbound and outbound). Can be overridden per-call via POST /v1/calls. */
    system_prompt?: string | null;
    /** Default opening line spoken on ALL calls (inbound and outbound), e.g. 'Hello, how can I help you today?'. Can be overridden per-call via POST /v1/calls. */
    initial_greeting?: string | null;
    /** TTS voice preset name (e.g. 'female-1', 'male-1') or Cartesia voice UUID; defaults to system voice if not set */
    voice_id?: string | null;
    /** Ignored unless it is the owner phone. Live transfers always dial owner_phone; a different number is rejected. */
    transfer_number?: string | null;
    /** Message the AI agent leaves if the call goes to voicemail */
    voicemail_message?: string | null;
    /** Owner's phone number in E.164 format (e.g. '+12125551234'). Calls from this number enter task mode. This is also the only number a live call can be transferred to. */
    owner_phone?: string | null;
}
