// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         agent_id: "agent_id"
 *     }
 */
export interface AgentUpdate {
    agent_id: string;
    /** New display name for the AI voice agent */
    name?: string | null;
    /** Updated default instructions for ALL future calls (does not affect calls already in progress) */
    system_prompt?: string | null;
    /** Updated default greeting for ALL future calls (inbound and outbound) */
    initial_greeting?: string | null;
    /** New TTS voice preset name or Cartesia voice UUID */
    voice_id?: string | null;
    /** Must match owner_phone. A different number is rejected; setting owner_phone updates this to the same number. */
    transfer_number?: string | null;
    /** Updated voicemail message */
    voicemail_message?: string | null;
    /** Updated owner phone in E.164. Also becomes the only live-call transfer destination. */
    owner_phone?: string | null;
}
