// This file was auto-generated by Fern from our API Definition.

export interface AccountWebhookConfig {
    url: string;
    secret?: (string | null) | undefined;
    signature_header?: (string | null) | undefined;
}
