// This file was auto-generated by Fern from our API Definition.

export interface Action {
    /** One of: buy_phone_number, create_agent, delete_agent, delete_webhook, hangup_call, make_outbound_call, release_phone_number, reset_account_voice, set_account_voice, set_webhook, submit_feedback, test_webhook, update_agent */
    operation: string;
    /** Named endpoint arguments; request fields go under body. Never include credentials. */
    arguments?: Record<string, unknown> | undefined;
    /** Stable caller-generated retry key; reuse for the same intended action. */
    request_id: string;
}
