// This file was auto-generated by Fern from our API Definition.

export interface AgentIdStartRequest {
    /** Optional AgentMail inbox, sent verbatim to AgentID as login_hint. Do not lowercase. Not required. */
    login_hint?: (string | null) | undefined;
}
