// This file was auto-generated by Fern from our API Definition.

export interface AgentOut {
    /** Unique agent identifier (e.g. 'agt_abc123') */
    id: string;
    /** Account that owns this agent */
    account_id: string;
    /** Display name of the AI voice agent */
    name: string;
    /** Default system prompt for all calls (can be overridden per-call) */
    system_prompt?: (string | null) | undefined;
    /** Default greeting for all calls (can be overridden per-call) */
    initial_greeting?: (string | null) | undefined;
    /** TTS voice preset or Cartesia UUID */
    voice_id?: (string | null) | undefined;
    /** Phone number for call transfers */
    transfer_number?: (string | null) | undefined;
    /** Message left on voicemail */
    voicemail_message?: (string | null) | undefined;
    /** Owner's phone number for task mode */
    owner_phone?: (string | null) | undefined;
    /** When the agent was created */
    created_at: string;
}
