// This file was auto-generated by Fern from our API Definition.

export interface CallContext {
    /** Facts for the voice agent to use in its own words. Not read aloud verbatim. Never include credentials. */
    context?: string | undefined;
    /** Open question to answer, from list_call_turns. Omit to add call facts at any time. */
    turn_id?: (string | null) | undefined;
    /** facts: call facts (or settles an open turn). partial: one fact so far, turn stays open. progress: not spoken. done/failed/noop: settle the turn. */
    disposition?: CallContext.Disposition | undefined;
}

export namespace CallContext {
    /** facts: call facts (or settles an open turn). partial: one fact so far, turn stays open. progress: not spoken. done/failed/noop: settle the turn. */
    export const Disposition = {
        Facts: "facts",
        Partial: "partial",
        Progress: "progress",
        Done: "done",
        Failed: "failed",
        Noop: "noop",
    } as const;
    export type Disposition = (typeof Disposition)[keyof typeof Disposition];
}
