// This file was auto-generated by Fern from our API Definition.

import type * as AgentlineApi from "../index.js";

export interface FeedbackCreate {
    /** Type of feedback: 'bug' (something broken / not working), 'feature_request' (want a new capability), 'difficulty' (hard or confusing to use), or 'feedback' (general comment or praise) */
    category: AgentlineApi.FeedbackCategory;
    /** Detailed description of the feedback, issue, or request. For bugs, include what you expected vs. what actually happened. */
    message: string;
    /** Short summary title for the feedback (optional) */
    subject?: (string | null) | undefined;
    /** Impact level, mainly relevant for bugs: 'low', 'normal', 'high', or 'critical' */
    severity?: AgentlineApi.FeedbackSeverity | undefined;
    /** ID of the AI agent this feedback relates to, if applicable */
    agent_id?: (string | null) | undefined;
    /** Email address for follow-up about this feedback (optional) */
    contact_email?: (string | null) | undefined;
}
