// This file was auto-generated by Fern from our API Definition.

export interface FeedbackOut {
    /** Unique feedback identifier (e.g. 'fb_abc123') */
    id: string;
    /** Account that submitted this feedback */
    account_id: string;
    /** Feedback type: 'bug', 'feature_request', 'difficulty', or 'feedback' */
    category: string;
    /** Full feedback message */
    message: string;
    /** Short summary title */
    subject?: (string | null) | undefined;
    /** Impact level: 'low', 'normal', 'high', or 'critical' */
    severity: string;
    /** Related AI agent ID, if any */
    agent_id?: (string | null) | undefined;
    /** Follow-up email, if provided */
    contact_email?: (string | null) | undefined;
    /** Current status: 'open', 'acknowledged', 'in_progress', 'resolved', or 'closed' */
    status: string;
    /** When the feedback was submitted */
    created_at: string;
}
