// This file was auto-generated by Fern from our API Definition.

export const FeedbackCategory = {
    Bug: "bug",
    FeatureRequest: "feature_request",
    Difficulty: "difficulty",
    Feedback: "feedback",
} as const;
export type FeedbackCategory = (typeof FeedbackCategory)[keyof typeof FeedbackCategory];
