// This file was auto-generated by Fern from our API Definition.

export const FeedbackSeverity = {
    Low: "low",
    Normal: "normal",
    High: "high",
    Critical: "critical",
} as const;
export type FeedbackSeverity = (typeof FeedbackSeverity)[keyof typeof FeedbackSeverity];
