// This file was auto-generated by Fern from our API Definition.

import type * as AgentlineApi from "../index.js";

export interface HttpValidationError {
    detail?: AgentlineApi.ValidationError[] | undefined;
}
