// This file was auto-generated by Fern from our API Definition.

/**
 * Partial agent update — only provided fields change (mirrors classic PATCH /v1/agents).
 */
export interface KeylessAgentUpdate {
    agent_name?: (string | null) | undefined;
    system_prompt?: (string | null) | undefined;
    initial_greeting?: (string | null) | undefined;
    voice_id?: (string | null) | undefined;
    transfer_number?: (string | null) | undefined;
    voicemail_message?: (string | null) | undefined;
    owner_phone?: (string | null) | undefined;
}
