// This file was auto-generated by Fern from our API Definition.

/**
 * Optional POST body for polling events (GET works identically).
 */
export interface KeylessEventsBody {
    phone_number?: (string | null) | undefined;
    event_type?: (string | null) | undefined;
    limit?: (number | null) | undefined;
    lease_token?: (string | null) | undefined;
}
