// This file was auto-generated by Fern from our API Definition.

export interface KeylessBuyBody {
    /** Display name for the voice agent */
    agent_name?: (string | null) | undefined;
    /** Personality/behavior instructions spoken on ALL calls */
    system_prompt?: (string | null) | undefined;
    /** Opening line spoken when a call connects */
    initial_greeting?: (string | null) | undefined;
    /** TTS voice preset (e.g. 'female-1') or Cartesia UUID */
    voice_id?: (string | null) | undefined;
    /** E.164 fallback number for call transfers */
    transfer_number?: (string | null) | undefined;
    /** Message left if the call goes to voicemail */
    voicemail_message?: (string | null) | undefined;
    /** Owner's E.164 phone — calls from it enter task mode */
    owner_phone?: (string | null) | undefined;
    /** Country code (only 'US' supported) */
    country?: string | undefined;
    /** 'local' or 'tollfree' */
    number_type?: string | undefined;
    /** Preferred 3-digit US area code */
    area_code?: (string | null) | undefined;
}
