// This file was auto-generated by Fern from our API Definition.

/**
 * Optional POST body for listing numbers (GET works identically).
 */
export interface KeylessListBody {
    /** Filter to one owned number */
    phone_number?: (string | null) | undefined;
    /** agent_... or lease_... access token */
    lease_token?: (string | null) | undefined;
}
