// This file was auto-generated by Fern from our API Definition.

/**
 * Optional POST body for transcripts (GET works identically).
 */
export interface KeylessTranscriptBody {
    lease_token?: (string | null) | undefined;
}
