// This file was auto-generated by Fern from our API Definition.

export interface KeylessWebhookBody {
    /** Your wallet-owned number whose agent gets the webhook */
    phone_number: string;
    /** HTTPS URL receiving the agent's events as signed JSON POSTs */
    url: string;
    /** HMAC signing secret (auto-generated if omitted) */
    secret?: (string | null) | undefined;
    /** HMAC header name (default 'X-Webhook-Signature') */
    signature_header?: (string | null) | undefined;
}
