// This file was auto-generated by Fern from our API Definition.

export interface KeylessCallBody {
    /** Your wallet-owned number (E.164, e.g. '+12125551234') */
    from_number: string;
    /** Destination phone number in E.164 format */
    to_number: string;
}
