// This file was auto-generated by Fern from our API Definition.

export interface OtpRequest {
    /** Email address to send the one-time code to. The same email identifies the account for both agents and humans. */
    email: string;
}
