// This file was auto-generated by Fern from our API Definition.

/**
 * Optional POST body for the discovery probe (GET works identically).
 */
export interface PayDiscoveryBody {
    /** Top-up amount in USD to advertise requirements for. */
    amount?: (number | null) | undefined;
}
