// This file was auto-generated by Fern from our API Definition.

export interface PayDiscoveryBody {
    /** Recharge USD amount, $1–$1000; defaults to $1. */
    amount?: (number | null) | undefined;
}
