// This file was auto-generated by Fern from our API Definition.

export interface VerifyRequest {
    /** Email address the one-time code was sent to */
    email: string;
    /** One-time code received via email */
    otp: string;
}
