// This file was auto-generated by Fern from our API Definition.

/**
 * What a webhook runtime supports on live relay calls (protocol v2).
 */
export interface WebhookCapabilities {
    /** Accepts call.task.amend POSTs: caller follow-ups on the open task, same turn_id, higher revision. When false, AgentLine holds follow-ups and sends them as one merged task after the current one settles. */
    supports_amend?: boolean | undefined;
    /** Accepts call.task.cancel POSTs when the caller withdraws a task. */
    supports_cancel?: boolean | undefined;
    /** Accepts call.session.start at call start and pushes facts the caller is likely to need (disposition=facts, no turn_id). */
    briefing?: boolean | undefined;
    /** Pushes partial/progress updates while it works. */
    streams_progress?: boolean | undefined;
}
