// This file was auto-generated by Fern from our API Definition.

/**
 * Returned on POST — exposes the full secret this one time.
 */
export interface WebhookCreated {
    /** Agent this webhook is scoped to */
    agent_id: string;
    /** Configured webhook URL */
    url: string;
    /** Full signing secret. Save it now — it is masked on subsequent reads. */
    secret: string;
    /** Header name used for HMAC-SHA256 signature delivery. */
    signature_header: string;
    /** When the webhook was last (re)configured */
    created_at?: (string | null) | undefined;
}
