// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         phone_number: "phone_number",
 *         agent_id: "agent_id"
 *     }
 */
export interface AttachNumbersRequest {
    phone_number: string;
    agent_id: string;
}
