// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         number_id: "number_id"
 *     }
 */
export interface GetNumbersRequest {
    number_id: string;
}
