// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         agent_id: "agent_id"
 *     }
 */
export interface NumberProvision {
    /** ID of the AI agent to assign this phone number to (e.g. 'agt_abc123') */
    agent_id: string;
    /** Country code for the phone number (currently only 'US' is supported) */
    country?: string;
    /** Type of phone number: 'local' or 'tollfree' */
    number_type?: string;
    /** Preferred 3-digit US area code (e.g. '212' for NYC, '415' for SF, '310' for LA) */
    area_code?: string | null;
    /** Legacy digit pattern match (prefer area_code instead) */
    pattern?: string | null;
}
