// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         number_id: "number_id",
 *         agent_id: "agent_id"
 *     }
 */
export interface ReassignNumbersRequest {
    number_id: string;
    agent_id: string;
}
