// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface PeekEventsRequest {
    /** Filter events by AI agent ID */
    agent_id?: string | null;
    /** Maximum number of events to preview (1-200) */
    limit?: number;
}
