// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface PollEventsRequest {
    /** Filter events by AI agent ID */
    agent_id?: string | null;
    /** Filter by event type (e.g. 'call.completed', 'call.failed') */
    event_type?: string | null;
    /** Maximum number of events to return (1-200) */
    limit?: number;
}
