// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         agent_id: "agent_id",
 *         to_number: "to_number"
 *     }
 */
export interface CallRequest {
    /** ID of the AI agent making the call (e.g. 'agt_abc123') */
    agent_id: string;
    /** Destination phone number in E.164 format (e.g. '+12125551234') */
    to_number: string;
    /** Per-call system prompt override. Replaces the agent's default prompt for this call ONLY. If omitted, the agent's default system_prompt is used. */
    system_prompt?: string | null;
    /** Per-call greeting override. Replaces the agent's default greeting for this call ONLY. If omitted, the agent's default initial_greeting is used. */
    initial_greeting?: string | null;
    /** Override the TTS voice for this call: preset name (e.g. 'female-1') or Cartesia UUID */
    voice_id?: string | null;
    /** Specific phone number ID to call from; defaults to the agent's assigned number */
    from_number_id?: string | null;
}
