// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         call_id: "call_id"
 *     }
 */
export interface GetTranscriptCallsRequest {
    call_id: string;
}
