// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListCallsRequest {
    /** Filter calls by AI agent ID */
    agent_id?: string | null;
    /** Filter by call status: 'initiated', 'in-progress', 'completed', or 'failed' */
    status?: string | null;
    /** Maximum number of calls to return (1-200) */
    limit?: number;
    /** Number of calls to skip for pagination */
    offset?: number;
}
