// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         call_id: "call_id",
 *         body: {
 *             "key": "value"
 *         }
 *     }
 */
export interface PushContextCallsRequest {
    call_id: string;
    /** Push token (alt to X-Push-Token header / body). */
    token?: string | null;
    "X-Push-Token"?: string | null;
    body: Record<string, unknown>;
}
