// This file was auto-generated by Fern from our API Definition.

import * as AgentlineApi from "../../src/api/index";
import { AgentLineClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("BillingClient", () => {
    test("get_balance", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/billing/balance")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.billing.getBalance();
        expect(response).toEqual(rawResponseBody);
    });

    test("get_expenditure (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/billing/expenditure")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.billing.getExpenditure();
        expect(response).toEqual(rawResponseBody);
    });

    test("get_expenditure (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/v1/billing/expenditure")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billing.getExpenditure();
        }).rejects.toThrow(AgentlineApi.UnprocessableEntityError);
    });

    test("list_call_charges (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/billing/expenditure/calls")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.billing.listCallCharges();
        expect(response).toEqual(rawResponseBody);
    });

    test("list_call_charges (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/v1/billing/expenditure/calls")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billing.listCallCharges();
        }).rejects.toThrow(AgentlineApi.UnprocessableEntityError);
    });

    test("list_number_charges (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/billing/expenditure/numbers")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.billing.listNumberCharges();
        expect(response).toEqual(rawResponseBody);
    });

    test("list_number_charges (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/v1/billing/expenditure/numbers")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billing.listNumberCharges();
        }).rejects.toThrow(AgentlineApi.UnprocessableEntityError);
    });

    test("get_summary (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/billing/summary")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.billing.getSummary();
        expect(response).toEqual(rawResponseBody);
    });

    test("get_summary (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/v1/billing/summary")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billing.getSummary();
        }).rejects.toThrow(AgentlineApi.UnprocessableEntityError);
    });
});
