// This file was auto-generated by Fern from our API Definition.

import * as AgentlineApi from "../../src/api/index";
import { AgentLineClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("CallsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/v1/calls").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.calls.list();
        expect(response).toEqual(rawResponseBody);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/v1/calls").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.calls.list();
        }).rejects.toThrow(AgentlineApi.UnprocessableEntityError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { agent_id: "agent_id", to_number: "to_number" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/calls")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.calls.create({
            agent_id: "agent_id",
            to_number: "to_number",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { agent_id: "agent_id", to_number: "to_number" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/v1/calls")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.calls.create({
                agent_id: "agent_id",
                to_number: "to_number",
            });
        }).rejects.toThrow(AgentlineApi.UnprocessableEntityError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/v1/calls/call_id").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.calls.get({
            call_id: "call_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/v1/calls/call_id").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.calls.get({
                call_id: "call_id",
            });
        }).rejects.toThrow(AgentlineApi.UnprocessableEntityError);
    });

    test("push_context (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { key: "value" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/calls/call_id/context")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.calls.pushContext({
            call_id: "call_id",
            body: {
                key: "value",
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("push_context (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { string: { key: "value" } };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/v1/calls/call_id/context")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.calls.pushContext({
                call_id: "call_id",
                body: {
                    string: {
                        key: "value",
                    },
                },
            });
        }).rejects.toThrow(AgentlineApi.UnprocessableEntityError);
    });

    test("hangup (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/calls/call_id/hangup")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.calls.hangup({
            call_id: "call_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("hangup (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/v1/calls/call_id/hangup")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.calls.hangup({
                call_id: "call_id",
            });
        }).rejects.toThrow(AgentlineApi.UnprocessableEntityError);
    });

    test("get_transcript (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/calls/call_id/transcript")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.calls.getTranscript({
            call_id: "call_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get_transcript (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/v1/calls/call_id/transcript")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.calls.getTranscript({
                call_id: "call_id",
            });
        }).rejects.toThrow(AgentlineApi.UnprocessableEntityError);
    });
});
