// This file was auto-generated by Fern from our API Definition.

import * as AgentlineApi from "../../src/api/index";
import { AgentLineClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("EventsClient", () => {
    test("poll (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/v1/events").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.events.poll();
        expect(response).toEqual(rawResponseBody);
    });

    test("poll (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/v1/events").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.events.poll();
        }).rejects.toThrow(AgentlineApi.UnprocessableEntityError);
    });

    test("peek (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/v1/events/peek").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.events.peek();
        expect(response).toEqual(rawResponseBody);
    });

    test("peek (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/v1/events/peek").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.events.peek();
        }).rejects.toThrow(AgentlineApi.UnprocessableEntityError);
    });
});
