// This file was auto-generated by Fern from our API Definition.

import * as AgentlineApi from "../../src/api/index";
import { AgentLineClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("MessagesClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/v1/messages").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.messages.list();
        expect(response).toEqual(rawResponseBody);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/v1/messages").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.messages.list();
        }).rejects.toThrow(AgentlineApi.UnprocessableEntityError);
    });

    test("send (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { agent_id: "agent_id", to_number: "to_number", body: "body" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/messages")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.messages.send({
            agent_id: "agent_id",
            to_number: "to_number",
            body: "body",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("send (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { agent_id: "agent_id", to_number: "to_number", body: "body" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/v1/messages")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.messages.send({
                agent_id: "agent_id",
                to_number: "to_number",
                body: "body",
            });
        }).rejects.toThrow(AgentlineApi.UnprocessableEntityError);
    });

    test("list_conversations (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/messages/conversations")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.messages.listConversations();
        expect(response).toEqual(rawResponseBody);
    });

    test("list_conversations (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/v1/messages/conversations")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.messages.listConversations();
        }).rejects.toThrow(AgentlineApi.UnprocessableEntityError);
    });
});
