// This file was auto-generated by Fern from our API Definition.

import * as AgentlineApi from "../../src/api/index";
import { AgentLineClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("NumbersClient", () => {
    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/v1/numbers").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.numbers.list();
        expect(response).toEqual(rawResponseBody);
    });

    test("buy (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { agent_id: "agent_id" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/numbers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.numbers.buy({
            agent_id: "agent_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("buy (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { agent_id: "agent_id" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/v1/numbers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.numbers.buy({
                agent_id: "agent_id",
            });
        }).rejects.toThrow(AgentlineApi.UnprocessableEntityError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/numbers/number_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.numbers.get({
            number_id: "number_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/v1/numbers/number_id")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.numbers.get({
                number_id: "number_id",
            });
        }).rejects.toThrow(AgentlineApi.UnprocessableEntityError);
    });

    test("reassign (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/v1/numbers/number_id/reassign")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.numbers.reassign({
            number_id: "number_id",
            agent_id: "agent_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("reassign (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/v1/numbers/number_id/reassign")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.numbers.reassign({
                number_id: "number_id",
                agent_id: "agent_id",
            });
        }).rejects.toThrow(AgentlineApi.UnprocessableEntityError);
    });
});
