// This file was auto-generated by Fern from our API Definition.

import * as AgentlineApi from "../../src/api/index";
import { AgentLineClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("VoiceClient", () => {
    test("get", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/v1/account/voice").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.voice.get();
        expect(response).toEqual(rawResponseBody);
    });

    test("reset", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/v1/account/voice")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.voice.reset();
        expect(response).toEqual(rawResponseBody);
    });

    test("set (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { voice_id: "voice_id" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/v1/account/voice")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.voice.set({
            voice_id: "voice_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("set (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { voice_id: "voice_id" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/v1/account/voice")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.voice.set({
                voice_id: "voice_id",
            });
        }).rejects.toThrow(AgentlineApi.UnprocessableEntityError);
    });

    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/v1/voices").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.voice.list();
        expect(response).toEqual(rawResponseBody);
    });
});
