// This file was auto-generated by Fern from our API Definition.

import * as AgentlineApi from "../../src/api/index";
import { AgentLineClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("WebhooksClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/v1/webhooks").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.webhooks.list();
        expect(response).toEqual(rawResponseBody);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/v1/webhooks").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.webhooks.list();
        }).rejects.toThrow(AgentlineApi.UnprocessableEntityError);
    });

    test("set (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { url: "url", agent_id: "agent_id" };
        const rawResponseBody = {
            agent_id: "agent_id",
            url: "url",
            secret: "secret",
            signature_header: "signature_header",
            created_at: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .post("/v1/webhooks")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.webhooks.set({
            url: "url",
            agent_id: "agent_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("set (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { url: "x", agent_id: "agent_id" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/v1/webhooks")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.set({
                url: "x",
                agent_id: "agent_id",
            });
        }).rejects.toThrow(AgentlineApi.UnprocessableEntityError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().delete("/v1/webhooks").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.webhooks.delete({
            agent_id: "agent_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().delete("/v1/webhooks").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.webhooks.delete({
                agent_id: "agent_id",
            });
        }).rejects.toThrow(AgentlineApi.UnprocessableEntityError);
    });

    test("test (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().post("/v1/webhooks/test").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.webhooks.test({
            agent_id: "agent_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("test (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentLineClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().post("/v1/webhooks/test").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.webhooks.test({
                agent_id: "agent_id",
            });
        }).rejects.toThrow(AgentlineApi.UnprocessableEntityError);
    });
});
