// This file was auto-generated by Fern from our API Definition.

import { AgentsClient } from "./api/resources/agents/client/Client.js";
import { BillingClient } from "./api/resources/billing/client/Client.js";
import { CallsClient } from "./api/resources/calls/client/Client.js";
import { EventsClient } from "./api/resources/events/client/Client.js";
import { MessagesClient } from "./api/resources/messages/client/Client.js";
import { NumbersClient } from "./api/resources/numbers/client/Client.js";
import { VoiceClient } from "./api/resources/voice/client/Client.js";
import { WebhooksClient } from "./api/resources/webhooks/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";
import * as core from "./core/index.js";

export declare namespace AgentLineClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class AgentLineClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<AgentLineClient.Options>;
    protected _voice: VoiceClient | undefined;
    protected _agents: AgentsClient | undefined;
    protected _billing: BillingClient | undefined;
    protected _calls: CallsClient | undefined;
    protected _events: EventsClient | undefined;
    protected _messages: MessagesClient | undefined;
    protected _numbers: NumbersClient | undefined;
    protected _webhooks: WebhooksClient | undefined;

    constructor(options: AgentLineClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get voice(): VoiceClient {
        return (this._voice ??= new VoiceClient(this._options));
    }

    public get agents(): AgentsClient {
        return (this._agents ??= new AgentsClient(this._options));
    }

    public get billing(): BillingClient {
        return (this._billing ??= new BillingClient(this._options));
    }

    public get calls(): CallsClient {
        return (this._calls ??= new CallsClient(this._options));
    }

    public get events(): EventsClient {
        return (this._events ??= new EventsClient(this._options));
    }

    public get messages(): MessagesClient {
        return (this._messages ??= new MessagesClient(this._options));
    }

    public get numbers(): NumbersClient {
        return (this._numbers ??= new NumbersClient(this._options));
    }

    public get webhooks(): WebhooksClient {
        return (this._webhooks ??= new WebhooksClient(this._options));
    }

    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    public async fetch(
        input: Request | string | URL,
        init?: RequestInit,
        requestOptions?: core.PassthroughRequest.RequestOptions,
    ): Promise<Response> {
        return core.makePassthroughRequest(
            input,
            init,
            {
                baseUrl: this._options.baseUrl ?? this._options.environment,
                headers: this._options.headers,
                timeoutInSeconds: this._options.timeoutInSeconds,
                maxRetries: this._options.maxRetries,
                fetch: this._options.fetch,
                logging: this._options.logging,
                getAuthHeaders: async () => (await this._options.authProvider.getAuthRequest()).headers,
            },
            requestOptions,
        );
    }
}
