// This file was auto-generated by Fern from our API Definition.

export const AgentlineApiEnvironment = {
    Production: "https://api.agentline.cloud",
} as const;

export type AgentlineApiEnvironment = typeof AgentlineApiEnvironment.Production;
